// Museframe builder — token-driven codegen of the briefed product.
// Everything is generated from the APPROVED design tokens except the CTA,
// which is deliberately pulled from a stale "legacy component library" that
// predates the token system. That makes drift REAL: the linter finds a genuine
// mismatch in genuinely generated code — nothing is staged in the UI layer.
// [HACKATHON: new work — written 2026-07-04 during RAISE]

import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { randomBytes } from 'node:crypto';

// The stale library. In a real codebase this is the three-year-old button.css
// nobody dares delete. Serif, sharp corners, off-system gold — pre-token era.
export const LEGACY_CTA_CSS = `.cta {
  font-family: Georgia, serif;
  font-weight: 400;
  border-radius: 4px;
  background: #c9a13b;
  color: #221d14;
  border: 1px solid #c9a13b;
  padding: 12px 30px;
  font-size: 15px;
  cursor: pointer;
}`;

export function tokenCtaCss(tokens) {
  return `.cta {
  font-family: ${tokens.font}, -apple-system, sans-serif;
  font-weight: 600;
  border-radius: ${tokens.radius};
  background: linear-gradient(90deg, ${tokens.acc}, ${tokens.acc2});
  color: #ffffff;
  border: 1px solid transparent;
  padding: 12px 30px;
  font-size: 15px;
  cursor: pointer;
}`;
}

export function build(board, workspaceDir) {
  const id = 'b' + randomBytes(4).toString('hex');
  const dir = join(workspaceDir, id);
  mkdirSync(dir, { recursive: true });
  const mood = board.moods.find(m => m.key === board.selected_mood) || board.moods[0];
  const t = mood.tokens;
  const reactive = board.motion.selected === 'reactive';
  const primary = board.components.find(c => c.primary) || board.components[1] || board.components[0];

  const html = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>${board.product.name} — ${board.product.tagline}</title>
<!-- generated by the Museframe harness · build ${id} · mood ${mood.key} · motion ${board.motion.selected} -->
<style>
/* @museframe:tokens — generated from the approved understanding board */
:root {
  --bg: ${t.bg}; --panel: ${t.panel}; --ink: ${t.ink}; --mut: ${t.mut};
  --acc: ${t.acc}; --acc2: ${t.acc2}; --line: ${t.line};
}
* { box-sizing: border-box; margin: 0; }
body {
  background: var(--bg); color: var(--ink); text-align: center;
  font-family: ${t.font}, -apple-system, sans-serif;
  padding: 44px 20px;
}
h1 { font-size: 40px; letter-spacing: -0.02em; }
.tagline { color: var(--mut); margin: 6px 0 26px; }
.surface {
  max-width: 680px; margin: 0 auto; background: var(--panel);
  border: 1px solid var(--line); border-radius: 16px; padding: 14px;
}
canvas { width: 100%; height: 140px; display: block; border-radius: 10px; background: color-mix(in srgb, var(--panel) 60%, var(--bg)); }
.surface-label { color: var(--mut); font-size: 12px; margin-top: 8px; text-transform: uppercase; letter-spacing: 0.12em; }
form { margin-top: 28px; display: flex; gap: 10px; justify-content: center; flex-wrap: wrap; }
input {
  background: var(--panel); color: var(--ink); border: 1px solid var(--line);
  border-radius: ${t.radius}; padding: 12px 18px; font: inherit; outline: none; min-width: 240px;
}
input:focus { border-color: var(--acc); }
/* @museframe:cta — imported from legacy-components v0.9 (pre-token library) */
${LEGACY_CTA_CSS}
footer { margin-top: 34px; color: var(--mut); font-size: 12px; }
</style>
</head>
<body>
  <h1>${board.product.name}</h1>
  <p class="tagline">${board.product.tagline}</p>
  <div class="surface">
    <canvas id="live" width="640" height="140"></canvas>
    <div class="surface-label">${primary.label} · ${board.motion.selected}</div>
  </div>
  <form onsubmit="return false">
    <input type="email" placeholder="you@wavelength.fm" aria-label="email">
    <button class="cta">Join the waitlist</button>
  </form>
  <footer>built by Museframe from an approved understanding board — not a template pick</footer>
<script>
  const cv = document.getElementById('live'), ctx = cv.getContext('2d');
  const REACTIVE = ${reactive};
  const N = 56, seeds = Array.from({ length: N }, () => Math.random() * 7);
  const css = getComputedStyle(document.documentElement);
  function frame(time) {
    const acc = css.getPropertyValue('--acc').trim(), acc2 = css.getPropertyValue('--acc2').trim();
    ctx.clearRect(0, 0, cv.width, cv.height);
    const bw = cv.width / N;
    for (let i = 0; i < N; i++) {
      const base = Math.sin(time / (REACTIVE ? 420 : 1400) + i * 0.32 + seeds[i]) * 0.5 + 0.5;
      const spike = REACTIVE ? Math.max(0, Math.sin(time / 130 + seeds[i] * 9)) * 0.45 : 0.05;
      const h = Math.max(4, (base * 0.55 + spike) * cv.height * 0.9);
      ctx.fillStyle = i % 6 === 0 ? acc2 : acc;
      ctx.globalAlpha = 0.35 + base * 0.65;
      ctx.beginPath();
      ctx.roundRect(i * bw + 1.5, cv.height - h, bw - 3, h, 3);
      ctx.fill();
    }
    ctx.globalAlpha = 1;
    requestAnimationFrame(frame);
  }
  requestAnimationFrame(frame);
</script>
</body>
</html>
`;
  writeFileSync(join(dir, 'index.html'), html);
  writeFileSync(join(dir, 'tokens.json'), JSON.stringify({
    build: id, mood: mood.key, motion: board.motion.selected, tokens: t,
    product: board.product, approved_at: new Date().toISOString(),
  }, null, 2));
  return { id, dir, mood: mood.key, motion: board.motion.selected };
}
